services:
  pluto:
    container_name: mcm_jl_pluto
    build:
      context: .
    image: radonnachie/mcm_jl:1.3.0
    volumes:
      - .:/work
    environment:
      - PWD=/work/notebooks/
    command: julia ./notebooks/pluto_serve.jl
    ports:
      - "1234:1234"
  benchmark:
    container_name: mcm_jl_benchmark
    image: radonnachie/mcm_jl:1.3.0
    volumes:
      - .:/work
    entrypoint: julia ./bin/mcm_benchmark.jl
  weigh_models:
    container_name: mcm_jl_weigh_in
    image: radonnachie/mcm_jl:1.3.0
    volumes:
      - .:/work
    entrypoint: julia ./bin/weigh_models.jl
  collate_results:
    container_name: mcm_jl_collate_results
    image: radonnachie/mcm_jl:1.3.0
    volumes:
      - .:/work
    entrypoint: julia ./bin/collate_results.jl
  na_upperbound_analyse:
    container_name: mcm_jl_na_upperbound_analyse
    image: radonnachie/mcm_jl:1.3.0
    volumes:
      - .:/work
    entrypoint: julia ./bin/upperbound_analysis.jl