services:
  mcm_jl_pluto:
    container_name: mcm_jl_pluto
    build:
      context: .
    image: radonnachie/mcm_jl:1.0
    volumes:
      - .:/work
    command: cd ./notebooks && julia ./pluto_serve.jl
    ports:
      - "1234:1234"
  mcm_jl_benchmark:
    container_name: mcm_jl_benchmark
    image: radonnachie/mcm_jl:1.0
    volumes:
      - .:/work
    command: julia ./bin/mcm_benchmark.jl
  read_result:
    container_name: read_result
    image: radonnachie/mcm_jl:1.0
    volumes:
      - .:/work
    command: julia ./bin/read.jl
  read_best:
    container_name: read_best
    image: radonnachie/mcm_jl:1.0
    volumes:
      - .:/work
    command: julia ./bin/read_best.jl
  analyse:
    container_name: analyse
    image: radonnachie/mcm_jl:1.0
    volumes:
      - .:/work
    command: julia ./bin/upperbound_analysis.jl