services:
  mcm_jl_pluto:
    container_name: mcm_jl_pluto
    build:
      context: .
    volumes:
      - .:/work
    command: julia ./notebooks/pluto_serve.jl
    ports:
      - "1234:1234"
  mcm_jl_benchmark:
    container_name: mcm_jl_benchmark
    build:
      context: .
    volumes:
      - .:/work
    command: julia ./src/mcm_benchmark.jl
  read_result:
    container_name: read_result
    build:
      context: .
    volumes:
      - .:/work
    command: julia ./src/read.jl
  read_best:
    container_name: read_best
    build:
      context: .
    volumes:
      - .:/work
    command: julia ./src/read_best.jl
  analyse:
    container_name: analyse
    build:
      context: .
    volumes:
      - .:/work
    command: julia ./src/meta_analysis.jl