services:
  mcm_jl_pluto:
    container_name: mcm_jl_pluto
    build:
      context: .
    image: radonnachie/mcm_jl:1.1.0
    volumes:
      - .:/work
    command: cd ./notebooks && julia ./pluto_serve.jl
    ports:
      - "1234:1234"
  mcm_benchmark:
    container_name: mcm_benchmark
    image: radonnachie/mcm_jl:1.1.0
    volumes:
      - .:/work
    entrypoint: julia ./bin/mcm_benchmark.jl
  collate_results:
    container_name: collate_results
    image: radonnachie/mcm_jl:1.1.0
    volumes:
      - .:/work
    entrypoint: julia ./bin/collate_results.jl
  na_upperbound_analyse:
    container_name: na_upperbound_analyse
    image: radonnachie/mcm_jl:1.1.0
    volumes:
      - .:/work
    entrypoint: julia ./bin/upperbound_analysis.jl